Similarity Search using FAISS on 512 dim cover photo embedding vectors

In [18]:
import faiss
import numpy as np

def similarity_search():
    xb = np.load(r"D:\Grailed_Npys\embeddings.npy", mmap_mode='r')
    d = 512
    index = faiss.IndexFlatL2(d)
    index.add(xb)
    k = 4
    D, I = index.search(xb[:5], k) # sanity check
    print(I)
    print(D)
similarity_search()

[[      0 1156984  592324 2718911]
 [      1     330     153 2517063]
 [      2      55 2238502 2238162]
 [      3     295 4344867 2238461]
 [      4    2320 4329434 3598026]]
[[0.         0.145895   0.15800571 0.15835047]
 [0.         0.25338244 0.26404834 0.27100825]
 [0.         0.20234871 0.24520612 0.26033115]
 [0.         0.43045974 0.44545174 0.4825946 ]
 [0.         0.27743006 0.27868915 0.27943122]]
